version: '3'
services:
    
    # PHP Service
    app:
        build: ./config/php
        container_name: CORE_PHP
        restart: unless-stopped
        tty: true
        env_file:
            - ".env"
        networks:
            - app-network
        volumes:
            - "./www:/var/www"
            - "./config/php/app.crontab:/etc/cron.d/app.crontab"
            - "./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
        command: [ "/bin/bash", "/usr/local/bin/start" ]
    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: CORE_NGINX
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-network
        volumes:
            - "/etc/ssl:/etc/ssl"
            - "/var/log/nginx:/var/log/nginx"
            - "./www:/var/www"
            - "./pdf:/var/pdf"
            - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./config/nginx/conf.d/:/etc/nginx/conf.d/:ro"

    #MySQL Service
    mysql:
        image: mysql:latest
        container_name: CORE_MYSQL
        restart: unless-stopped
        tty: true
        #expose:
        #    - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 123456789
        networks:
            - app-network
        volumes:
            - dbdata:/var/lib/mysql
           #- "var/run/mysqld:var/run/mysqld"
            - "./config/mysql/my.cnf:/etc/mysql/my.cnf"

#Docker Networks
networks:
    app-network:
        driver: bridge

#Docker Volumes
volumes:
    dbdata:
        driver: local
